[[book]]
field = []
AAAA = [3, 2]
AAAB = [2, 3]
AABB = [3, 3]
AABC = [2, 3]  # [1, 2], [3, 3], [2, 3]?
ABAA = [3, 0]  # [2, 0], [3, 0]?
ABAB = [2, 2]
ABAC = [3, 0]  # TODO {1, 1] ?
ABCC = [2, 2]  # [2, 2]? [3, 1]?

[[book]]
field = [
    "..A...",
    "..A..."
]
AAAA = [5, 2]
AAAB = [3, 0]
AAAC = [3, 0]
AABB = [3, 0]
AABC = [3, 0]

[[book]]
field = [
    "A.....",
    "A....."
]
BCAA = [2, 2]
BCAB = [2, 2]
BCAC = [2, 0]
BCBB = [2, 0]
BCBC = [2, 2]

[[book]]
field = [
    ".AA..."
]
ABAB = [1, 0]
ABAC = [1, 0]
ABBB = [1, 0]
ABBC = [1, 0]
ABCC = [4, 2]
BBAA = [3, 3] # [1, 2]? [3, 3]?
BBAC = [3, 3]
BBBB = [3, 3]
BBBC = [3, 3]
BBCC = [3, 3]
BCAB = [2, 0]

[[book]]
field = [
    "AA...."
]
ABAA = [3, 0]
ABAB = [3, 0]
ABAC = [3, 0] # [3, 0], [1, 1]
ABBC = [3, 0] # [3, 0], [1, 1]
ABCC = [3, 2]
ABBB = [3, 0]
BCBB = [3, 0]
BCAB = [3, 1]

[[book]]
field = [
    "AB...."
]
ACAA = [1, 1]
ACAB = [1, 1]
ACAC = [1, 1]
ACBB = [1, 1]
ACBC = [1, 1]
ACCC = [1, 1]

[[book]]
field = [
    "..AB.."
]
CCAC = [2, 3]
CCBC = [2, 3]

[[book]]
field = [
    "..B...",
    "..A..."
]
AAAA = [2, 3]
AAAB = [2, 3]
AABB = [2, 3]
AAAC = [2, 3]
AABC = [2, 3]
AACC = [2, 3]
ABAB = [2, 0]
ACAA = [4, 2]  # [2, 3]? [4, 2]?
ACAB = [1, 0]
ACBB = [4, 2]  # [4, 2] looks bad... [1, 0]?
ACBC = [2, 3]
ACAC = [2, 3]  # [1, 0]? [2, 3]?
ACCC = [2, 3]

[[book]]
field = [
    ".B....",
    ".A...."
]
AAAC = [1, 2]
AABC = [1, 2]
ABAA = [3, 0]
ABAB = [3, 0]
ABAC = [1, 0]
ABBB = [3, 0]
ABCC = [1, 0] # [3, 0]?
ABBC = [3, 0]
CCAB = [1, 2] # [5, 1]?
CCAC = [1, 2]
CCBC = [5, 1]
CCCC = [1, 2]

# ----------------------------------------------------------------------

[[book]]
field = [
    "AABC.."
]
CCBD = [5, 1]

[[book]]
field = [
    "AC....",
    "AB...."
]
AABC = [2, 2]
ABBB = [2, 3]  # TODO: [2, 1]? [2, 3]
ABAD = [2, 3]
ABBD = [2, 3]
ABCC = [1, 1]
ABDD = [2, 3]  # TODO: [1, 1]?
ACAA = [1, 1]
ACAB = [1, 1]
ACAC = [1, 1]
ACAD = [1, 1]
ACBB = [1, 1]
ACBC = [2, 3]
ACBD = [1, 1]
ACCC = [1, 1]
ACDD = [1, 1]  # [5, 3]?
BBCB = [1, 2]
BBCC = [1, 2]
BBDD = [3, 1]
BCBB = [3, 0]
BCBC = [3, 0]
BCAC = [3, 0]
BDAB = [3, 1]

[[book]]
field = [
    ".BB...",
    ".AA..."
]
AAAC = [5, 1]  # TODO: [2, 3] ?
AACC = [5, 1]  # TODO: [2, 3] ?
ABAB = [1, 0]  # [2, 2] is faster, but if AB comes again, taking 1-rensa double is big.
ABAC = [1, 0]
ABBB = [1, 0]
ABBC = [1, 0]
ACAB = [4, 2]
ACAC = [4, 2]
ACAD = [4, 2]
ACCC = [1, 0]
ACDD = [1, 0]
BBAC = [4, 1]
BBBC = [5, 1]  # [4, 1]? [5, 1]?
BBCC = [4, 1]
BCAA = [1, 0]
BCAC = [1, 0]  # [1, 0], [4, 1]?
BCAD = [1, 0]  # [1, 0]? [4, 0]?
BCBC = [1, 0]
BCBD = [4, 0]  # [1, 0]? [4, 0]? [4, 1]?
BCCC = [4, 0]
BCCD = [4, 1]
CCAC = [1, 2]
CCBC = [5, 1]
CCBD = [1, 2]
CCCC = [1, 2]

[[book]]
field = [
    "BB....",
    "AA...."
]
ACAA = [3, 2]
ACAB = [3, 2]
ACAC = [3, 2]
ACAD = [3, 2]
ACBC = [2, 0]
ACBD = [3, 2]

[[book]]
field = [
    "B.....",
    "AAA...",
]
ABBC = [2, 2]
ACAB = [4, 2]
ACAD = [4, 2]  # TODO: [3, 2] ?
BCBD = [2, 0]

[[book]]
field = [
    "..B...",
    "AAA..."
]
AABC = [5, 1]
ABAB = [2, 2]
ABAC = [2, 2] # [2, 2]? [3, 3]?
ABBC = [2, 2]
ABCC = [2, 2]
ABCD = [2, 2]
ACAB = [4, 2]
ACAC = [4, 2]
ACAD = [4, 2]
ACBB = [4, 2]
ACBC = [4, 2]
ACBD = [4, 2]
ACCC = [4, 2]
ACDD = [4, 2]
BBBC = [2, 3]
BBCC = [2, 3]
BBCD = [2, 3]
BBAC = [2, 3]
BCAB = [1, 0]
BCAD = [1, 0]
BCAC = [4, 1]
BCBD = [1, 0]
BCCC = [2, 3]
BCCD = [2, 3]
BCDD = [1, 0]
CCAB = [5, 1]  # TODO: [1, 2] ?
CCAC = [2, 3]  # [5, 1]?

[[book]]
field = [
    "AB....",
    "AA...."
]
ACBC = [2, 3]
BBBC = [3, 1]

[[book]]
field = [
    "..C...",
    "ABB..."
]
ACAC = [1, 1]
ACAD = [1, 1]
ACBC = [1, 1]
AAAC = [5, 1]
AAAB = [5, 1]
AAAD = [1, 2]
BBBC = [5, 1]
BBBD = [5, 1]

[[book]]
field = [
    "..CA..",
    "..AB.."
]
AABD = [2, 3]
CCAA = [2, 3]
CCCB = [2, 3]

[[book]]
field = [
    "..A...",
    "AAB..."
]
CCAD = [2, 3]

[[book]]
field = [
    "B.C...",
    "A.A..."
]
ABBB = [2, 0]
ABCD = [2, 0]
ABBC = [2, 0]
ACAB = [2, 0]
ACBB = [2, 0]
ACBD = [2, 0]
ACCC = [2, 0]
ACCD = [2, 0]
ACDD = [2, 0]

[[book]]
field = [
    "A.....",
    "A.BC.."
]
ABAD = [2, 0]

[[book]]
field = [
    "C.....",
    "A.....",
    "AB...."
]
BBAD = [3, 2]

[[book]]
field = [
    "B.....",
    "A.C...",
    "ABB..."
]
ACAA = [2, 2]

# ----------------------------------------------------------------------

[[book]]
field = [
    "BBB...",
    "AAA..."
]
ACAD = [4, 2]
ACBC = [3, 3]
ADAD = [4, 2]
BCAB = [4, 0]
BCBD = [4, 0]
BCCC = [2, 2]
CCAB = [2, 3]
CCDD = [5, 1]
CDBC = [6, 0]

[[book]]
field = [
    ".A....",
    ".BB...",
    "AAA..."
]
BCAB = [1, 0]
BCBC = [4, 1]
BCCD = [4, 1]
BCDD = [1, 0]
CCCD = [5, 1]

[[book]]
field = [
    ".C....",
    ".BB...",
    "AAA..."
]
ABBD = [1, 2]

[[book]]
field = [
    "C.....",
    "B.B...",
    "AAA..."
]
DDAD = [5, 1]

[[book]]
field = [
    ".BB...",
    ".AA.AA"
]
ACDD = [4, 2]

[[book]]
field = [
    "..B...",
    "AAA.AA"
]
BCBD = [1, 0]

[[book]]
field = [
    ".BB...",
    ".AABB."
]
BCBD = [6, 0]

[[book]]
field = [
    "BBC...",
    "AAA..."
]
BCBB = [3, 1]
ADAD = [2, 0]
CDBB = [4, 0]

[[book]]
field = [
    "BCC...",
    "AAA...",
]
ABBC = [2, 3]
ABBD = [4, 2] # other?
ABAC = [2, 3]
ADBB = [4, 2]
ADBC = [4, 2]
ADBD = [4, 2] # [2, 0]?
CDAD = [4, 1] # [2, 0]? [4, 1]?
CDBC = [4, 0]
CCCD = [4, 1]
DDAC = [5, 1]

[[book]]
field = [
      "CAA...",
      "ABB..."
]
BCCD = [3, 3]
BDAB = [4, 2]

[[book]]
field = [
    "ACC...",
    "ABB...",
]
ABAB = [2, 3]
ACBC = [3, 1]
ADBC = [3, 0]
CDCD = [4, 1]

[[book]]
field = [
    "..CA..",
    "AAAB..",
]
CDAC = [1, 0]
DDAC = [5, 1] # [5, 1], [1, 2]?

[[book]]
field = [
    "C.....",
    "CC....",
    "AAB...",
]
CDCD = [5, 0] # or [5, 0]? [5, 2]?

[[book]]
field = [
    ".CC...",
    ".AA.BB"
]
ABAB = [4, 2]

[[book]]
field = [
    "CC....",
    "AA.BB."
]
ACCD = [3, 0]

[[book]]
field = [
    "C.....",
    "B.B...",
    "AAA..."
]
ACCC = [4, 2]
ADAC = [4, 2]
BDAB = [4, 1]

[[book]]
field = [
    "CCA...",
    "AAB...",
]
ABAB = [2, 1]

[[book]]
field = [
    ".AAC..",
    ".CCB..",
]
CDCD = [3, 1]

[[book]]
field = [
    ".BB...",
    ".AABC."
]
CDCD = [6, 0]
DDAC = [1, 2]

[[book]]
field = [
    ".B....",
    ".AABCC",
]
BDCD = [3, 0]  # TODO: other?

[[book]]
field = [
    "..B...",
    "AAABC."
]
ACDD = [6, 2]

[[book]]
field = [
    "CA....",
    "AC....",
    "AB...."
]
BDCD = [3, 1]

[[book]]
field = [
    "AC....",
    "AC....",
    "AB...."
]
ACCC = [2, 3]

[[book]]
field = [
    "......",
    "..AB..",
    "AABC.."
]
ACBC = [4, 1]

[[book]]
field = [
    "......",
    "..C...",
    "ABB.AA"
]
ABBD = [4, 2]

[[book]]
field = [
    "......",
    "..C...",
    "ABB.BB"
]
ACBD = [1, 1]
BDBB = [4, 2]

[[book]]
field = [
    "......",
    "..B...",
    "AAA.AA"
]
CCBB = [5, 1]
ACDD = [3, 1]

# ----------------------------------------------------------------------

[[book]]
field = [
    "CCBD..",
    "AAAB.."
]
CCAB = [6, 2]

[[book]]
field = [
    ".AA...",
    "ACC...",
    "ABB..."
]
ADAD = [6, 2]
ADBD = [6, 2]

[[book]]
field = [
    "BA....",
    "ACC...",
    "ABB..."
]
AABC = [3, 2]  # for ZENKESHI
ABAA = [2, 3]
BBAD = [5, 1]
BBAC = [1, 2]

[[book]]
field = [
    "CA....",
    "ACC...",
    "ABB..."
]
CCAB = [1, 2]

[[book]]
field = [
    "BA....",
    "BBC...",
    "AAA..."
]
ADBD = [6, 2]

[[book]]
field = [
    "BA....",
    "BCC...",
    "AAA..."
]
BCAC = [2, 1]  # For ZENKESHI


[[book]]
field = [
    "AB....",
    "ACC...",
    "ABB..."
]
ABAC = [2, 3]  # For ZENKESHI
DDAC = [5, 1]

[[book]]
field = [
    "..CA..",
    "AAABAA"
]
BCBD = [1, 2]
