[mode.default.move]

RENSA_KIND = 2
FALLEN_OJAMA = -50
TOTAL_FRAMES = -0.1
NUM_CHIGIRI = -50
CONNECTION_2 = 15
CONNECTION_3 = 45
CONNECTION_HORIZONTAL_2 = 50
CONNECTION_HORIZONTAL_3 = 100
CONNECTION_HORIZONTAL_CROSSED_2 = -50
CONNECTION_HORIZONTAL_CROSSED_3 = -100
THIRD_COLUMN_HEIGHT = [
        0,     0,     0,   -30,   -40,   -50,   -60,   -70,   -80,  -200,
    -2000, -7000, -9000, -9000, -9000, -9000]
STRATEGY_FRAMES = -100
STRATEGY_KILL = 350000
# STRATEGY_LARGE_ENOUGH = 300000
STRATEGY_LARGE_ENOUGH = 1000
STRATEGY_ZENKESHI = 500
STRATEGY_TAIOU = 100000
STRATEGY_TAIOU_RELUCTANT = 30000
STRATEGY_TSUBUSHI = 80000
STRATEGY_SAKIUCHI = -1500
STRATEGY_LAND_LEVELING = 0
STRATEGY_SCORE = 0.1
STRATEGY_SOLO_ZENKESHI_CONSUME = 100000
STRATEGY_IBARA = 0
STRATEGY_RENSA_TREE = 0
STRATEGY_RENSA_TREE_NEGATIVE = 10
VALLEY_DEPTH = [0, 0, -15, -20, -2000, -3000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000]
VALLEY_DEPTH_EDGE = [0, -30, -50, -700, -2000, -3000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000]
RIDGE_HEIGHT = [0, 0, -15, -20, -2000, -3000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000]
FIELD_USHAPE_LINEAR = -0.1
FIELD_USHAPE_SQUARE = -1.6
NUM_UNREACHABLE_SPACE = -2000
MIDEVAL_ERASE = -1800
MIDEVAL_RESULT = 0.0001
KEEP_FAST_LARGER_THEN_ENEMY = 1000
KEEP_FAST_4_CHAIN = 300
KEEP_FAST_6_CHAIN = 300
KEEP_FAST_10_CHAIN = 500
# KEEP_FAST_4_CHAIN = 1000
# KEEP_FAST_6_CHAIN = 1300
# KEEP_FAST_10_CHAIN = 200
NUM_COUNT_OJAMA = -50

[mode.default.main]
PATTERN_BOOK = 10
PATTERN_BOOK_DIV_RENSA = 40
RENSA_FIELD_USHAPE_LINEAR = 0
RENSA_FIELD_USHAPE_SQUARE = -5
RENSA_VALLEY_DEPTH = [0, 0, -15, -20, -2000, -3000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000]
RENSA_VALLEY_DEPTH_EDGE = [0, -10, -15, -20, -2000, -3000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000, -4000]
MAX_CHAINS = [
     0,  1000,  2000,  3000,  4000,  5000,  6000,  7000,  8000,  9000,
 10000, 11000, 12000, 13000, 14000, 15000, 16000, 17000, 18000, 19000,
]
NECESSARY_PUYOS_LINEAR = -80
NECESSARY_PUYOS_SQUARE = -6
COMPLEMENTATION_BIAS = -50
COMPLEMENTATION_BIAS_EDGE = -700
COMPLEMENTATION_BIAS_MUCH = -50
CONNECTION_AFTER_DROP_2 = 1
CONNECTION_AFTER_DROP_3 = 3
FIRE_POINT_TABOO = -120
IGNITION_HEIGHT = [0, 0, 0, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330]
NUM_GARBAGE_PUYOS = -5
NUM_SIDE_GARBAGE_PUYOS = -20
SCORE = 0
VIRTUAL_SCORE = 0
STRATEGY_SAISOKU = 8500
HIGHER_PUYO_THAN_IGNITION_LINEAR = -6
HIGHER_PUYO_THAN_IGNITION_SQUARE = -7

[mode.default.side]
NECESSARY_PUYOS_LINEAR = 0

[mode.initial.move]
NUM_CHIGIRI = -100
THIRD_COLUMN_HEIGHT = [
        0,     0,     0,     0,     0,     0,     0,   -70,   -80,  -200,
    -2000, -7000, -9000, -9000, -9000, -9000]
KEEP_FAST_6_CHAIN = 800
KEEP_FAST_10_CHAIN = 800
STRATEGY_ZENKESHI = 50000

[mode.initial.main]
PATTERN_BOOK = 130
PATTERN_BOOK_DIV_RENSA = 200
NUM_PLACE_HOLDERS = -70
NECESSARY_PUYOS_LINEAR = -220
NECESSARY_PUYOS_SQUARE = -15

[mode.initial.side]
NECESSARY_PUYOS_LINEAR = 0

[mode.early.move]
NUM_CHIGIRI = -100
THIRD_COLUMN_HEIGHT = [
        0,     0,     0,     0,     0,     0,     0,   -70,   -80,  -200,
    -2000, -7000, -9000, -9000, -9000, -9000]
KEEP_FAST_6_CHAIN = 800
KEEP_FAST_10_CHAIN = 800
STRATEGY_ZENKESHI = 5000
STRATEGY_RENSA_TREE = 0
HOLDING_SIDE_CHAIN_SMALL  = 1800
HOLDING_SIDE_CHAIN_MEDIUM = 2000
HOLDING_SIDE_CHAIN_LARGE  = 2300

[mode.early.main]
PATTERN_BOOK = 110
PATTERN_BOOK_DIV_RENSA = 200
NUM_PLACE_HOLDERS = -70
NECESSARY_PUYOS_LINEAR = -220
NECESSARY_PUYOS_SQUARE = -15

[mode.early.side]
NECESSARY_PUYOS_LINEAR = 0

[mode.middle.move]
HOLDING_SIDE_CHAIN_SMALL  = 2300
HOLDING_SIDE_CHAIN_MEDIUM = 2500
HOLDING_SIDE_CHAIN_LARGE  = 2800
STRATEGY_FIRE_SIDE_CHAIN_2_LARGE = 4000
STRATEGY_FIRE_SIDE_CHAIN_2_MEDIUM = 3500
STRATEGY_FIRE_SIDE_CHAIN_2_SMALL = 2500
STRATEGY_FIRE_SIDE_CHAIN_3_LARGE = 3000
STRATEGY_FIRE_SIDE_CHAIN_3_MEDIUM = 2000
STRATEGY_FIRE_SIDE_CHAIN_3_SMALL = 1500
STRATEGY_IBARA = 20000
STRATEGY_RENSA_TREE = 0

[mode.middle.main]
PATTERN_BOOK = 70
PATTERN_BOOK_DIV_RENSA = 80
NECESSARY_PUYOS_LINEAR = -220
NECESSARY_PUYOS_SQUARE = -15

[mode.middle.side]
NECESSARY_PUYOS_LINEAR = 0


[mode.late.move]
HOLDING_SIDE_CHAIN_SMALL  = 3100
HOLDING_SIDE_CHAIN_MEDIUM = 3400
HOLDING_SIDE_CHAIN_LARGE  = 3700
STRATEGY_FIRE_SIDE_CHAIN_2_LARGE = 6000
STRATEGY_FIRE_SIDE_CHAIN_2_MEDIUM = 5000
STRATEGY_FIRE_SIDE_CHAIN_2_SMALL = 4000
STRATEGY_FIRE_SIDE_CHAIN_3_LARGE = 4500
STRATEGY_FIRE_SIDE_CHAIN_3_MEDIUM = 4000
STRATEGY_FIRE_SIDE_CHAIN_3_SMALL = 3000
STRATEGY_IBARA = 20000
STRATEGY_RENSA_TREE = 0

[mode.late.main]
PATTERN_BOOK = 20
PATTERN_BOOK_DIV_RENSA = 100
NECESSARY_PUYOS_LINEAR = -250
NECESSARY_PUYOS_SQUARE = -15
VIRTUAL_SCORE = 0.3

[mode.late.side]
NECESSARY_PUYOS_LINEAR = 0


[mode.enemy_has_zenkeshi.move]
STRATEGY_ZENKESHI = 50000
STRATEGY_ZENKESHI_CONSUME = 100000
FIELD_USHAPE_LINEAR = 0
FIELD_USHAPE_SQUARE = 0
FIELD_RIGHT_BIAS_LINEAR = -10
FIELD_RIGHT_BIAS_SQUARE = -50
THIRD_COLUMN_HEIGHT = [
        0,     0,     0,     0,     0,     0,     0,   -6000,   -6000,  -6000,
    -6000, -7000, -9000, -9000, -9000, -9000]

[mode.enemy_has_zenkeshi.main]
RENSA_FIELD_USHAPE_LINEAR = 0
RENSA_FIELD_USHAPE_SQUARE = 0
IGNITION_HEIGHT = [0, 100, 200, 300, 400, 500, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700]

[mode.enemy_has_zenkeshi.side]
NECESSARY_PUYOS_LINEAR = 0

[mode.enemy_has_zenkeshi_middle.move]
STRATEGY_ZENKESHI = 50000
STRATEGY_ZENKESHI_CONSUME = 100000
FIELD_USHAPE_LINEAR = 0
FIELD_USHAPE_SQUARE = 0
FIELD_RIGHT_BIAS_LINEAR = -10
FIELD_RIGHT_BIAS_SQUARE = -50
THIRD_COLUMN_HEIGHT = [
        0,     0,     0,     0,     0,     0,     0,   -6000,   -6000,  -6000,
    -6000, -7000, -9000, -9000, -9000, -9000]

[mode.enemy_has_zenkeshi_middle.main]
RENSA_FIELD_USHAPE_LINEAR = 0
RENSA_FIELD_USHAPE_SQUARE = 0
IGNITION_HEIGHT = [0, 100, 200, 300, 400, 500, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700]

[mode.enemy_has_zenkeshi_middle.side]
NECESSARY_PUYOS_LINEAR = 0
