name = "fire because large enough"

[me]
field = [
      ".....B",
      "....BB",
      "...BRR",
      "RYGRBR",
      "RRYGGG",
      "YYGBBB"
]
next = "RYGGRR"

[enemy]
field = []
next = "RRYYGG"

[answer]
answers = [
    [1, 0],
    [1, 1],
]
