# 定積
# 初手 --------------------
[[book]]
field = []
AAAA = [3, 2]
AAAB = [3, 3]
AABB = [3, 3]
AABC = [1, 2]
ABAA = [3, 0]
ABAB = [3, 0]
ABAC = [3, 0]
ABCC = [2, 2]

# 2手目 --------------------
[[book]]
field = [
    "..A...",
    "..A..."
]
AA   = [3, 0]
AAAA = [5, 2]

[[book]]
field = [
    "A.....",
    "A....."
]
BC   = [2, 2]
BCBB = [2, 0]

[[book]]
field = [
    ".AA..."
]
AB = [1, 0]
BB = [3, 3]

[[book]]
field = [
    "..B...",
    "..A..."
]
AA = [2, 3]
AB = [2, 0]
AC = [2, 3]
ACAC = [1, 0]

[[book]]
field = [
    ".B....",
    ".A...."
]
CC = [1, 2]

# 3手目---------------------

[[book]]
field = [
    "AC....",
    "AB...."
]
AA = [2, 2]
AB = [1, 1]
AC = [1, 1]
BB = [3, 1]
BC = [3, 0]
CC = [3, 2]

[[book]]
field = [
    ".BB...",
    ".AA..."
]
AA = [2, 3]
AB = [1, 0]
AC = [1, 0]
BB = [4, 1]
BC = [1, 0]
CC = [3, 2]  # not sure

[[book]]
field = [
    "B.....",
    "AAA...",
]
AB = [2, 2]
AC = [4, 2] # for 新GTR-left

[[book]]
field = [
    "..C...",
    "ABB..."
]
AA = [1, 2]
AB = [1, 2]
AC = [1, 1]
BB = [5, 1]
BC = [1, 1]
CC = [4, 1]

[[book]]
field = [
    "C.B...",
    "A.A..."
]
AC = [2, 0]
